image: 192.168.16.36:5000/cicd

stages:
  - lint
  - test
  {%- if cookiecutter.sphinx_docs == "y" %}
  - docs
  {%- endif %}
  - deploy

lint:
  before_script:
    - pyenv local 3.6.7 3.7.6 3.8.7
    - python -V
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
  stage: lint
  script:
    - pip install -e .[dev]
    - pre-commit run -a
    - invoke lint-commit
  tags:
    - docker
    - local

test:
  before_script:
    - pyenv local 3.6.7 3.7.6 3.8.7
    - python -V
  stage: test
  script:
    - tox
  tags:
    - docker
    - local

{%- if cookiecutter.sphinx_docs == "y" %}

build_docs:
  before_script:
    - pyenv local 3.6.7 3.7.6 3.8.7
    - python -V
  stage: docs
  script:
    - tox -e docs
  artifacts:
    paths:
      - docs/_build
    expire_in: 3 day
  tags:
    - docker
    - local
  only:
    - tags

{%- endif %}

deploy:
  before_script:
    - pyenv local 3.6.7 3.7.6 3.8.7
    - python -V
  stage: deploy
  script:
    - python setup.py sdist upload -r devpi
    - python setup.py sdist upload -r local
    {%- if cookiecutter.sphinx_docs == "y" %}
    - python setup.py upload_docs --upload-dir docs/_build -r devpi
    {%- endif %}
  dependencies:
    - build_docs
  tags:
    - docker
    - local
  only:
    - tags
